[package]
name = "blittle"
version = "0.5.0"
edition = "2024"
description = "A fast little blitter"
authors = ["Esther Alter <subalterngames@gmail.com>"]
readme = "README.md"
repository = "https://github.com/subalterngames/blittle"
license-file = "LICENSE"
keywords = ["blitting", "image", "sprite", "gamedev", "graphics"]
categories = ["game-development", "graphics", "rendering"]

[dependencies]
bytemuck = "1.25.0"
glam = { version = "0.32.1", features = ["bytemuck"]}
png =  { version = "0.18.1", optional = true }
raw-window-handle = { version = "0.6.2", optional = true }
serde = { version = "1", features = ["derive"], optional = true}
softbuffer = { version = "0.4.8", optional = true }
thiserror = "2.0.18"

[dev-dependencies]
blit = "0.8.5"
criterion = "0.8.2"
sdl2 = "0.38.0"

[[bench]]
name = "convert"
harness = false

[[bench]]
name = "crates"
harness = false

[[bench]]
name = "mask"
harness = false

[features]
png = ["dep:png"]
serde = ["dep:serde", "glam/serde"]
softbuffer = ["dep:raw-window-handle", "dep:softbuffer"]

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
