[package]
name = "blittle"
version = "0.7.1"
edition = "2024"
description = "A fast little blitter"
authors = ["Esther Alter <subalterngames@gmail.com>"]
readme = "README.md"
repository = "https://github.com/subalterngames/blittle"
license-file = "LICENSE"
keywords = ["blitting", "image", "sprite", "gamedev", "graphics"]
categories = ["game-development", "graphics", "rendering"]

[dependencies]
bytemuck = { version = "1.25.0", optional = true }
paste = "1.0.15"
png =  { version = "0.18.1", optional = true }
raw-window-handle = { version = "0.6.2", optional = true }
serde = { version = "1", features = ["derive"], optional = true}
softbuffer = { version = "0.4.8", optional = true }
thiserror = "2.0.18"

[dev-dependencies]
blit = "0.8.5"
criterion = "0.8.2"
sdl2 = "0.38.0"

[features]
default = ["std"]
bytes = ["dep:bytemuck", "std"]
png = ["bytes", "dep:png", "std"]
serde = ["dep:serde"]
softbuffer = ["dep:bytemuck", "dep:raw-window-handle", "dep:softbuffer", "std"]
std = []

[[bench]]
name = "blend"
harness = false
required-features = ["png"]

[[bench]]
name = "convert"
harness = false
required-features = ["std"]

[[bench]]
name = "crates"
harness = false
required-features = ["std"]

[[bench]]
name = "mask"
harness = false
required-features = ["std"]

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]
