[package]
name = "blittle"
version = "0.1.0"
edition = "2024"

[dependencies]
rayon = { version = "1.11.0", optional = true }

[dev-dependencies]
bytemuck = "1.24.0"
criterion = "0.7.0"
png = "0.18.0"

[features]
rayon = ["dep:rayon"]

[[bench]]
name = "bench"
harness = false