[package]
name = "blittle"
version = "0.1.0"
edition = "2024"

[dependencies]
memx = "0.2.0"
rayon = { version = "1.11.0", optional = true }

[dev-dependencies]
blit = "0.8.5"
bytemuck = "1.24.0"
criterion = "0.7.0"
png = "0.18.0"
sdl2 = "0.38.0"

[[bench]]
name = "bench"
harness = false
